services:
  - type: web
    name: calcus-demo
    runtime: image
    repo: https://github.com/Thirugnanam2001/calcus_demo  # Replace with your repo URL
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /
    autoDeploy: true